from deepgram import DeepgramClient, PrerecordedOptions
from flask import Flask, request, Response
from flask_sockets import Sockets
from dotenv import load_dotenv
import base64
import json
import os
# from transcriber import TwilioTranscriber

load_dotenv()


PORT = 5000
DEBUG = False
INCOMING_CALL_ROUTE = '/' # Endpoint in our app where TWilio looks for code when we receive a call
WEBSCOKET_ROUTE = '/realtime' # Route of the websocket where audio stream will be sent 
DEEPGRAM_API_KEY = os.getenv("DEEPGRAM_API_KEY")
# We have to give the customer's voice to this AUDIO_URL which we are getting from 
AUDIO_URL = os.getenv("NGROK_URL")


app = Flask(__name__)
sockets = Sockets(app)
ngrok_URL = os.getenv("NGROK_URL") # Link for public url, which is generated by ngrok using Flask



@app.route(INCOMING_CALL_ROUTE, methods=['GET', 'POST'])
def receive_call():
    if request.method == 'POST':
        xml = f""" 
        <Response>
            <Start>
                <Stream url={ngrok_URL} />
            </Start>
            <Say>Streaming live audio to your WebSocket server.</Say>
        </Response>
        """.strip()
        return Response(xml, mimetype='text/xml')
    else:
        return "Hello, World!"

@sockets.route(WEBSCOKET_ROUTE)
def transcription_websocket(ws):
    while True:
        data = json.loads(ws.receive())
        match data['event']:
            case "connected":
                # transcriber = TwilioTranscriber()
                # transcriber.connect()
                print('transcriber connected')
            case "start":
                print('twilio started')
            case "media": 
                # payload_b64 = data['media']['payload']
                # payload_mulaw = base64.b64decode(payload_b64)
                print("Media accessed")
                # transcriber.stream(payload_mulaw)
            case "stop":
                print('twilio stopped')
                # transcriber.close()
                # print('transcriber closed')


def speech_to_text():
    try:
        #Speech to Text
        deepgram = DeepgramClient(DEEPGRAM_API_KEY)

        options = PrerecordedOptions(
            model="nova-2",
            language="en",
            smart_format=True,
        )

        response = deepgram.listen.prerecorded.v("1").transcribe_url(AUDIO_URL, options)
        print(response.to_json(indent=4))
        with open('response.json', 'w') as json_file:
            json.dump(response, json_file, indent=4)

    except Exception as e:
        print(f"Exception: {e}")

if __name__ == '__main__':
    app.run(port=PORT, debug=DEBUG)
    speech_to_text()

